import { db } from "./db";
import { portfolioProjects, blogPosts, services, reviews, heroContent, siteSettings } from "@shared/schema";
import { sql } from "drizzle-orm";

export async function seedDatabase() {
  const existing = await db.select().from(portfolioProjects);
  if (existing.length > 0) {
    console.log("Database already seeded, skipping...");
    return;
  }

  console.log("Seeding database...");

  await db.insert(portfolioProjects).values([
    {
      slug: "modern-kitchen-backsplash",
      titleNo: "Moderne kjøkken flislegging",
      titleEn: "Modern Kitchen Backsplash",
      shortDescriptionNo: "Elegant sildebensmønster i marmor for en luksuriøs kjøkkenoppussing",
      shortDescriptionEn: "Elegant herringbone marble backsplash for a luxury kitchen renovation",
      descriptionNo: "Denne fantastiske kjøkkenoppussingen inneholdt en spesialtilpasset sildebensmønster i marmor som forvandlet hele matlagingsområdet. Huseieren ønsket et tidløst, men moderne utseende.\n\nVi valgte premium Calacatta-marmorfliser og installerte dem i et klassisk sildebensmønster som gir visuell interesse og dybde til kjøkkenet.",
      descriptionEn: "This stunning kitchen renovation featured a custom herringbone marble backsplash that transformed the entire cooking space. The homeowner wanted a timeless yet modern look.\n\nWe selected premium Calacatta marble tiles and installed them in a classic herringbone pattern that adds visual interest and depth to the kitchen.",
      categoryNo: "Kjøkken",
      categoryEn: "Kitchen",
      coverImage: "/images/portfolio-kitchen-backsplash.png",
      images: ["/images/portfolio-kitchen-floor.png"],
      featured: true,
    },
    {
      slug: "luxury-bathroom-renovation",
      titleNo: "Luksuriøs baderomoppussing",
      titleEn: "Luxury Bathroom Renovation",
      shortDescriptionNo: "Komplett baderomstransformasjon med gulv-til-tak porselensfliser",
      shortDescriptionEn: "Complete bathroom transformation with floor-to-ceiling porcelain tiles",
      descriptionNo: "En komplett hovedbadsoppussing med store porselensfliser gjennom hele rommet. Dette prosjektet viste vår evne til å håndtere komplekse planløsninger med presisjon og oppmerksomhet på detaljer.",
      descriptionEn: "A complete master bathroom renovation featuring large-format porcelain tiles throughout. This project showcased our ability to handle complex layouts with precision and attention to detail.",
      categoryNo: "Baderom",
      categoryEn: "Bathroom",
      coverImage: "/images/portfolio-bathroom-floor.png",
      images: ["/images/portfolio-shower-mosaic.png", "/images/portfolio-master-bath.png"],
      featured: true,
    },
    {
      slug: "outdoor-patio-transformation",
      titleNo: "Utendørs terrasse-transformasjon",
      titleEn: "Outdoor Patio Transformation",
      shortDescriptionNo: "Naturstein som skaper et fantastisk utendørs oppholdsområde",
      shortDescriptionEn: "Natural stone pavers creating a stunning outdoor living area",
      descriptionNo: "Dette utendørs oppholdsområdet ble forvandlet med vakre travertinfliser, og skapte en elegant terrasse perfekt for underholdning.",
      descriptionEn: "This outdoor living space was transformed with beautiful travertine pavers, creating an elegant patio perfect for entertaining.",
      categoryNo: "Utendørs",
      categoryEn: "Outdoor",
      coverImage: "/images/portfolio-patio-tiles.png",
      images: [],
      featured: true,
    },
    {
      slug: "shower-mosaic-feature-wall",
      titleNo: "Dusj mosaikk-aksentvegg",
      titleEn: "Shower Mosaic Feature Wall",
      shortDescriptionNo: "Spesialtilpasset glassmosaikk aksentvegg i et moderne dusjkabinett",
      shortDescriptionEn: "Custom glass mosaic accent wall in a modern shower enclosure",
      descriptionNo: "Denne spesialtilpassede dusjoppussingen har en fantastisk glassmosaikk aksentvegg som fungerer som fokuspunkt for hele baderommet.",
      descriptionEn: "This custom shower renovation features a breathtaking glass mosaic accent wall that serves as the focal point of the entire bathroom.",
      categoryNo: "Baderom",
      categoryEn: "Bathroom",
      coverImage: "/images/portfolio-shower-mosaic.png",
      images: ["/images/portfolio-bathroom-floor.png"],
      featured: true,
    },
    {
      slug: "grand-entryway-floor-design",
      titleNo: "Storslått entré gulvdesign",
      titleEn: "Grand Entryway Floor Design",
      shortDescriptionNo: "Geometrisk naturstein flismønster for et fantastisk førsteinntrykk",
      shortDescriptionEn: "Geometric natural stone tile pattern for a stunning first impression",
      descriptionNo: "Denne storslåtte entréen har et spesialtilpasset geometrisk flismønster med naturstein, som skaper et fantastisk førsteinntrykk.",
      descriptionEn: "This grand entryway features a custom geometric tile pattern using natural stone, creating a stunning first impression.",
      categoryNo: "Gulv",
      categoryEn: "Flooring",
      coverImage: "/images/portfolio-entryway.png",
      images: ["/images/portfolio-kitchen-floor.png"],
      featured: false,
    },
    {
      slug: "kitchen-floor-renovation",
      titleNo: "Kjøkkengulv oppussing",
      titleEn: "Kitchen Floor Renovation",
      shortDescriptionNo: "Store porselensfliser for et moderne, åpent kjøkken",
      shortDescriptionEn: "Large format porcelain tiles for a modern open-concept kitchen",
      descriptionNo: "Denne kjøkkengulvoppussingen forvandlet et utdatert rom med store porselensfliser i en varm grå tone.",
      descriptionEn: "This kitchen floor renovation transformed an outdated space with large-format porcelain tiles in a warm gray tone.",
      categoryNo: "Kjøkken",
      categoryEn: "Kitchen",
      coverImage: "/images/portfolio-kitchen-floor.png",
      images: ["/images/portfolio-kitchen-backsplash.png"],
      featured: false,
    },
    {
      slug: "master-bath-marble-retreat",
      titleNo: "Hovedbad marmor-oase",
      titleEn: "Master Bath Marble Retreat",
      shortDescriptionNo: "Gulv-til-tak marmor flislegging med frittstående badekar",
      shortDescriptionEn: "Floor-to-ceiling marble tile installation with freestanding tub surround",
      descriptionNo: "Dette hovedbadet ble forvandlet til en ekte marmor-oase, med gulv-til-tak Carrara marmorfliser og et fantastisk frittstående badekar.",
      descriptionEn: "This master bathroom was transformed into a true marble retreat, featuring floor-to-ceiling Carrara marble tiles and a stunning freestanding bathtub surround.",
      categoryNo: "Baderom",
      categoryEn: "Bathroom",
      coverImage: "/images/portfolio-master-bath.png",
      images: ["/images/portfolio-bathroom-floor.png", "/images/portfolio-shower-mosaic.png"],
      featured: false,
    },
  ]);

  await db.insert(blogPosts).values([
    {
      slug: "choosing-kitchen-backsplash-tile",
      titleNo: "Hvordan velge riktig flis til kjøkkenet",
      titleEn: "How to Choose the Right Tile for Your Kitchen Backsplash",
      excerptNo: "En komplett guide til å velge riktig flismateriale, størrelse og mønster for ditt kjøkkenprosjekt.",
      excerptEn: "A comprehensive guide to selecting the perfect tile material, size, and pattern for your kitchen backsplash project.",
      contentNo: "Kjøkkenveggen bak benken er en av de mest synlige designelementene i hjemmet ditt.\n\n## Vurder kjøkkenstilen din\n\nFørste steg er å tenke på den generelle stilen i kjøkkenet ditt. Moderne kjøkken ser bra ut med store fliser, rene linjer og nøytrale farger.\n\n## Populære flismaterialer\n\n- Keramikk: Rimelig og tilgjengelig i utallige farger\n- Porselen: Mer holdbar enn keramikk\n- Naturstein: Marmor, travertin og skifer gir unik karakter\n- Glass: Gir dybde og reflekterer lys vakkert",
      contentEn: "Your kitchen backsplash is one of the most visible design elements in your home.\n\n## Consider Your Kitchen Style\n\nThe first step is to think about the overall style of your kitchen. Modern kitchens look great with large-format tiles, clean lines, and neutral colors.\n\n## Popular Tile Materials\n\n- Ceramic: Affordable and available in countless colors\n- Porcelain: More durable than ceramic\n- Natural Stone: Marble, travertine, and slate offer unique character\n- Glass: Adds depth and reflects light beautifully",
      coverImage: "/images/blog-tile-selection.png",
      categoryNo: "Guider",
      categoryEn: "Guides",
    },
    {
      slug: "bathroom-renovation-mistakes",
      titleNo: "5 baderomoppussing feil du bør unngå",
      titleEn: "5 Bathroom Renovation Mistakes to Avoid",
      excerptNo: "Lær av vanlige fallgruver ved baderomoppussing som kan koste deg tid, penger og hodepine.",
      excerptEn: "Learn from common bathroom renovation pitfalls that can cost you time, money, and headaches.",
      contentNo: "Baderomoppussing er spennende, men kan raskt gå galt hvis du ikke er forsiktig.\n\n## 1. Hoppe over riktig vanntetting\n\nDette er den største feilen huseiere gjør.\n\n## 2. Velge stil fremfor funksjon\n\nVurder holdbarhet, sklisikkerhet og vedlikeholdskrav når du velger fliser.",
      contentEn: "Bathroom renovations are exciting but can quickly go wrong if you're not careful.\n\n## 1. Skipping Proper Waterproofing\n\nThis is the biggest mistake homeowners make.\n\n## 2. Choosing Style Over Function\n\nConsider durability, slip resistance, and maintenance requirements when selecting your tiles.",
      coverImage: "/images/blog-renovation-tips.png",
      categoryNo: "Tips",
      categoryEn: "Tips",
    },
    {
      slug: "complete-guide-tile-flooring",
      titleNo: "Komplett guide til flisgulv",
      titleEn: "The Complete Guide to Tile Flooring",
      excerptNo: "Alt du trenger å vite om flisgulv, fra materialvalg til installasjonsprosessen.",
      excerptEn: "Everything you need to know about tile flooring, from material selection to the installation process.",
      contentNo: "Flisgulv er et av de mest holdbare og allsidige gulvalternativene som finnes.\n\n## Hvorfor velge flisgulv?\n\nFlisgulv tilbyr mange fordeler. Det er utrolig holdbart, vanntett, lett å rengjøre.\n\n## Typer gulvfliser\n\n- Porselen: Gullstandarden for holdbarhet\n- Keramikk: Et budsjettvennlig alternativ\n- Naturstein: Unik skjønnhet",
      contentEn: "Tile flooring is one of the most durable and versatile flooring options available.\n\n## Why Choose Tile Flooring?\n\nTile flooring offers numerous advantages. It's incredibly durable, water-resistant, easy to clean.\n\n## Types of Floor Tiles\n\n- Porcelain: The gold standard for durability\n- Ceramic: A budget-friendly option\n- Natural Stone: Unique beauty",
      coverImage: "/images/blog-tile-selection.png",
      categoryNo: "Tjenester",
      categoryEn: "Services",
    },
    {
      slug: "trending-tile-designs-2025",
      titleNo: "Trendy flisdesign for 2025",
      titleEn: "Trending Tile Designs for 2025",
      excerptNo: "Oppdag de nyeste flistrendene for 2025, fra dristige mønstre til innovative materialer.",
      excerptEn: "Discover the latest tile design trends for 2025, from bold patterns to innovative materials.",
      contentNo: "Flisindustrien er i stadig utvikling.\n\n## Store fliser dominerer\n\nStørre er fortsatt bedre når det gjelder flisstørrelse.\n\n## Teksturerte og 3D-fliser\n\nFlate fliser viker for tredimensjonale overflater.",
      contentEn: "The tile industry is constantly evolving.\n\n## Large-Format Tiles Continue to Dominate\n\nBigger is still better when it comes to tile size.\n\n## Textured and 3D Tiles\n\nFlat tiles are giving way to three-dimensional surfaces.",
      coverImage: "/images/blog-renovation-tips.png",
      categoryNo: "Trender",
      categoryEn: "Trends",
    },
  ]);

  await db.insert(services).values([
    {
      slug: "kitchen-tiling",
      titleNo: "Kjøkkenflislegging",
      titleEn: "Kitchen Tiling",
      excerptNo: "Profesjonell flislegging av kjøkkenvegger og gulv med premium materialer",
      excerptEn: "Professional kitchen wall and floor tiling with premium materials",
      contentNo: "Vi tilbyr komplett kjøkkenflislegging med fokus på kvalitet og holdbarhet.\n\n## Våre kjøkkentjenester\n\n- Backsplash installasjon\n- Gulvfliser\n- Benkeplatearbeid\n- Mønsterlegging",
      contentEn: "We offer complete kitchen tiling with a focus on quality and durability.\n\n## Our kitchen services\n\n- Backsplash installation\n- Floor tiling\n- Countertop work\n- Pattern laying",
      image: "/images/portfolio-kitchen-backsplash.png",
      icon: "ChefHat",
      featured: true,
    },
    {
      slug: "bathroom-renovation",
      titleNo: "Baderomoppussing",
      titleEn: "Bathroom Renovation",
      excerptNo: "Komplett baderomstransformasjon med vanntetting og premium fliser",
      excerptEn: "Complete bathroom transformation with waterproofing and premium tiles",
      contentNo: "Vi spesialiserer oss på komplett baderomoppussing.\n\n## Våre baderomsjenester\n\n- Gulv-til-tak flislegging\n- Vanntetting\n- Dusjkabinett\n- Mosaikk aksentvegger",
      contentEn: "We specialize in complete bathroom renovation.\n\n## Our bathroom services\n\n- Floor-to-ceiling tiling\n- Waterproofing\n- Shower enclosures\n- Mosaic accent walls",
      image: "/images/portfolio-bathroom-floor.png",
      icon: "Bath",
      featured: true,
    },
    {
      slug: "floor-tiling",
      titleNo: "Gulvflislegging",
      titleEn: "Floor Tiling",
      excerptNo: "Profesjonell gulvflislegging for alle rom med ulike materialer",
      excerptEn: "Professional floor tiling for all rooms with various materials",
      contentNo: "Vårt team installerer gulvfliser i alle rom.\n\n## Gulvtjenester\n\n- Storformat fliser\n- Naturstein installasjon\n- Mønsterlegging\n- Varmekabler",
      contentEn: "Our team installs floor tiles in all rooms.\n\n## Floor services\n\n- Large format tiles\n- Natural stone installation\n- Pattern laying\n- Underfloor heating",
      image: "/images/portfolio-entryway.png",
      icon: "Layers",
      featured: true,
    },
    {
      slug: "outdoor-tiling",
      titleNo: "Utendørs flislegging",
      titleEn: "Outdoor Tiling",
      excerptNo: "Holdbare utendørs flisløsninger for terrasser og innganger",
      excerptEn: "Durable outdoor tiling solutions for patios and entrances",
      contentNo: "Vi tilbyr profesjonell utendørs flislegging som tåler norske værforhold.\n\n## Utendørstjenester\n\n- Terrasse flislegging\n- Inngangspartier\n- Trapper og trinn\n- Drenering og fall",
      contentEn: "We offer professional outdoor tiling that withstands Nordic weather.\n\n## Outdoor services\n\n- Patio tiling\n- Entrance areas\n- Stairs and steps\n- Drainage and slope",
      image: "/images/portfolio-patio-tiles.png",
      icon: "Sun",
      featured: true,
    },
    {
      slug: "mosaic-art",
      titleNo: "Mosaikk og kunstnerisk flisarbeid",
      titleEn: "Mosaic & Artistic Tilework",
      excerptNo: "Spesialtilpassede mosaikkdesign for unike rom",
      excerptEn: "Custom mosaic designs for unique spaces",
      contentNo: "Vi skaper unike, spesialtilpassede mosaikkdesign.\n\n## Mosaikktjenester\n\n- Aksentvegger\n- Dusjnisjer\n- Gulvmedaljonger\n- Spesialtilpassede mønstre",
      contentEn: "We create unique, custom mosaic designs.\n\n## Mosaic services\n\n- Accent walls\n- Shower niches\n- Floor medallions\n- Custom patterns",
      image: "/images/portfolio-shower-mosaic.png",
      icon: "Palette",
      featured: false,
    },
  ]);

  await db.insert(reviews).values([
    {
      authorName: "Sarah Mitchell",
      rating: 5,
      textNo: "Helt utrolig arbeid på kjøkkenveggen vår! Sildebensmønsteret i marmor er fantastisk. Teamet var profesjonelt, punktlig og etterlot arbeidsområdet plettfritt.",
      textEn: "Absolutely incredible work on our kitchen backsplash! The herringbone marble pattern is stunning. The team was professional, punctual, and left the workspace spotless.",
      featured: true,
    },
    {
      authorName: "James Rodriguez",
      rating: 5,
      textNo: "Vi hyret Max Flis & Bad for hovedbadsoppussingen vår og kunne ikke vært lykkeligere. Oppmerksomheten på detaljer er bemerkelsesverdig.",
      textEn: "We hired Max Flis & Bad for our master bathroom renovation and couldn't be happier. The attention to detail is remarkable.",
      featured: true,
    },
    {
      authorName: "Emily Chen",
      rating: 5,
      textNo: "Beste flisleggere i byen! De forvandlet vårt utdaterte baderom til en moderne spa-lignende oase. Rettferdige priser og utmerket kommunikasjon.",
      textEn: "Best tile installers in town! They transformed our outdated bathroom into a modern spa-like retreat. Fair pricing and excellent communication.",
      featured: true,
    },
    {
      authorName: "Michael Thompson",
      rating: 4,
      textNo: "Flott arbeid med terrasse-flisleggingen vår. Natursteinene ser vakre ut og har holdt seg perfekt gjennom vinteren.",
      textEn: "Great work on our patio tile installation. The natural stone pavers look beautiful and have held up perfectly through the winter.",
      featured: true,
    },
    {
      authorName: "Lisa Park",
      rating: 5,
      textNo: "Max Flis & Bad gjorde en fantastisk jobb med entré-gulvet vårt. Det geometriske mønsteret er helt nydelig.",
      textEn: "Max Flis & Bad did an amazing job on our entryway floor. The geometric pattern they created is absolutely stunning.",
      featured: true,
    },
    {
      authorName: "David Williams",
      rating: 5,
      textNo: "Fikk hele kjøkkengulvet lagt om og resultatet er fantastisk. Store porselensfliser med minimale fuglinjer - akkurat det vi ønsket.",
      textEn: "Had our entire kitchen floor retiled and the result is fantastic. Large format porcelain tiles with minimal grout lines - exactly what we wanted.",
      featured: true,
    },
  ]);

  await db.insert(heroContent).values([
    {
      pageKey: "home",
      titleNo: "Ekspert flislegging som forvandler rom",
      titleEn: "Expert Tile Installation That Transforms Spaces",
      subtitleNo: "15+ års erfaring",
      subtitleEn: "15+ Years of Excellence",
      descriptionNo: "Max Flis & Bad AS leverer førsteklasses flislegging for kjøkken, bad, gulv og utendørs prosjekter.",
      descriptionEn: "Max Flis & Bad AS delivers premium tile installation for kitchens, bathrooms, floors, and outdoor projects.",
    },
    {
      pageKey: "portfolio",
      titleNo: "Vår portefølje",
      titleEn: "Our Portfolio",
      subtitleNo: "Se våre siste prosjekter",
      subtitleEn: "Browse our recent projects",
      descriptionNo: "Utforsk vårt utvalg av flisleggingsprosjekter.",
      descriptionEn: "Explore our selection of tile installation projects.",
    },
    {
      pageKey: "blog",
      titleNo: "Blogg og artikler",
      titleEn: "Blog & Articles",
      subtitleNo: "Tips, guider og inspirasjon",
      subtitleEn: "Tips, guides and inspiration",
      descriptionNo: "Les våre siste artikler om flislegging og designtrender.",
      descriptionEn: "Read our latest articles about tiling and design trends.",
    },
    {
      pageKey: "services",
      titleNo: "Våre tjenester",
      titleEn: "Our Services",
      subtitleNo: "Profesjonell flislegging for alle behov",
      subtitleEn: "Professional tiling for every need",
      descriptionNo: "Vi tilbyr et komplett utvalg av flisleggingstjenester.",
      descriptionEn: "We offer a complete range of tiling services.",
    },
    {
      pageKey: "contact",
      titleNo: "Kontakt oss",
      titleEn: "Contact Us",
      subtitleNo: "Vi hører gjerne fra deg",
      subtitleEn: "We'd love to hear from you",
      descriptionNo: "Ta kontakt for et uforpliktende prisoverslag.",
      descriptionEn: "Get in touch for a free estimate.",
    },
  ]);

  await db.insert(siteSettings).values([
    { key: "business_name", valueNo: "Max Flis & Bad AS", valueEn: "Max Flis & Bad AS" },
    { key: "phone", valueNo: "+47 123 45 678", valueEn: "+47 123 45 678" },
    { key: "email", valueNo: "post@maxflisbad.no", valueEn: "post@maxflisbad.no" },
    { key: "address", valueNo: "Eksempelveien 1, 0001 Oslo, Norge", valueEn: "Eksempelveien 1, 0001 Oslo, Norway" },
    { key: "business_hours", valueNo: "Man-Fre: 08:00 - 16:00", valueEn: "Mon-Fri: 08:00 - 16:00" },
    { key: "instagram_url", valueNo: "https://instagram.com/maxflisbad", valueEn: "https://instagram.com/maxflisbad" },
    { key: "facebook_url", valueNo: "https://facebook.com/maxflisbad", valueEn: "https://facebook.com/maxflisbad" },
    { key: "meta_description", valueNo: "Max Flis & Bad AS - Profesjonell flislegging i Oslo. Kjøkken, bad, gulv og utendørs. 15+ års erfaring.", valueEn: "Max Flis & Bad AS - Professional tile installation in Oslo. Kitchen, bathroom, floor and outdoor. 15+ years of experience." },
  ]);

  console.log("Seeding complete!");
}
